version: '2.1'
networks:
  localnet:
    driver: bridge

services:
  main_web:
    build: ./main_app
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      market_data_service:
        condition: service_started
      rabbit:
        condition: service_healthy
    links:
      - rabbit
    networks:
      - localnet

  market_data_service:
    build: ./market_data_service
    restart: on-failure
    depends_on:
      rabbit:
        condition: service_healthy
    links:
      - rabbit
    networks:
      - localnet

  rabbit:
    build: ./tuned_rabbitmq
    ports:
      - "15672:15672"
      - "15671:15671"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - localnet
